"""
analysis/analyze.py — Standalone P&L / pattern analysis for the sniper_bot_v2
backtest output. This file is ADDITIVE: it never imports, modifies, or runs the
existing engine. It only READS the CSVs the backtester already produced.

What it does
------------
Reads  data/backtest/trade_log.csv  (and equity_curve.csv if present) and
aggregates the trades into the slices a trader actually wants to see:

  * Per-MONTH P&L         -> "trading-chart" candles (green = profit month,
                             red = loss month). Body = open->close equity,
                             wick = intramonth min/max running equity.
  * Per-YEAR P&L          -> yearly bars.
  * Day-of-week pattern   -> which weekday pays best.
  * Hour-of-entry pattern -> which entry hour pays best.
  * Calendar heatmap      -> Year x Month grid coloured by P&L.
  * Direction split       -> LONG vs SHORT performance.
  * Equity curve          -> cumulative P&L over time (drawdown shaded).
  * Headline metrics      -> trades, win rate, total P&L, profit factor, etc.

Outputs (all written into analysis/output/, nothing else is touched):
  analysis/output/analysis.json   <- machine-readable aggregates
  (the dashboard HTML is generated by build_dashboard.py, which calls this)

Usage:
  python analysis/analyze.py
  python analysis/analyze.py --trades path/to/trade_log.csv
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TRADES = ROOT / "data" / "backtest" / "trade_log.csv"
DEFAULT_EQUITY = ROOT / "data" / "backtest" / "equity_curve.csv"
OUT_DIR = Path(__file__).resolve().parent / "output"

MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
DOW_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def load_trades(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Only realized outcomes carry P&L (matches the engine's compute_metrics).
    df = df[df["result"].isin(["WIN", "LOSS", "FLAT"])].copy()
    # Anchor every trade on its EXIT (when P&L is actually booked); fall back
    # to entry time if exit is blank.
    df["exit_time"] = pd.to_datetime(df["exit_time"], errors="coerce")
    df["entry_time"] = pd.to_datetime(df["entry_time"], errors="coerce")
    df["t"] = df["exit_time"].fillna(df["entry_time"])
    df = df.dropna(subset=["t"]).sort_values("t").reset_index(drop=True)

    df["pnl"] = pd.to_numeric(df["pnl"], errors="coerce").fillna(0.0)
    df["r_gained"] = pd.to_numeric(df["r_gained"], errors="coerce").fillna(0.0)
    df["year"] = df["t"].dt.year
    df["month"] = df["t"].dt.month
    df["ym"] = df["t"].dt.strftime("%Y-%m")
    df["dow"] = df["t"].dt.dayofweek          # 0 = Monday
    df["entry_hour"] = df["entry_time"].dt.hour
    df["is_win"] = df["pnl"] > 0
    return df


def _profit_factor(pnls: pd.Series) -> float:
    gains = pnls[pnls > 0].sum()
    losses = -pnls[pnls < 0].sum()
    if losses == 0:
        return float(gains) if gains else 0.0
    return round(float(gains / losses), 3)


def _group_block(df: pd.DataFrame, by: str) -> list[dict]:
    """Generic grouped stats used for dow / hour / direction breakdowns."""
    rows = []
    for key, g in df.groupby(by):
        rows.append({
            "key": key,
            "trades": int(len(g)),
            "wins": int((g["pnl"] > 0).sum()),
            "win_rate": round(100 * (g["pnl"] > 0).mean(), 1),
            "pnl": round(float(g["pnl"].sum()), 2),
            "avg_pnl": round(float(g["pnl"].mean()), 2),
            "total_r": round(float(g["r_gained"].sum()), 3),
        })
    return rows


def build_monthly_candles(df: pd.DataFrame) -> list[dict]:
    """
    Turn each calendar month into an OHLC-style 'candle' on the EQUITY curve:
      open  = cumulative equity at the start of the month
      close = cumulative equity at the end of the month
      high  = max running equity reached during the month
      low   = min running equity reached during the month
    So a green candle = the account grew that month; a red one = it shrank,
    and the wick shows the intramonth swing. This is the "real trading chart"
    view of monthly performance.
    """
    df = df.sort_values("t").copy()
    df["cum"] = df["pnl"].cumsum()
    df["cum_prev"] = df["cum"].shift(1).fillna(0.0)

    candles = []
    for ym, g in df.groupby("ym"):
        o = float(g["cum_prev"].iloc[0])
        c = float(g["cum"].iloc[-1])
        hi = float(g["cum"].max())
        lo = float(g["cum"].min())
        # The wick should also account for the open level.
        hi = max(hi, o)
        lo = min(lo, o)
        candles.append({
            "ym": ym,
            "open": round(o, 2),
            "high": round(hi, 2),
            "low": round(lo, 2),
            "close": round(c, 2),
            "month_pnl": round(c - o, 2),
            "trades": int(len(g)),
            "win_rate": round(100 * (g["pnl"] > 0).mean(), 1),
            "up": c >= o,
        })
    return candles


def build_calendar(df: pd.DataFrame) -> dict:
    """Year x Month P&L grid for a heatmap."""
    years = sorted(df["year"].unique().tolist())
    grid = {}
    for y in years:
        row = []
        for m in range(1, 13):
            sub = df[(df["year"] == y) & (df["month"] == m)]
            row.append({
                "pnl": round(float(sub["pnl"].sum()), 2) if len(sub) else None,
                "trades": int(len(sub)),
            })
        grid[str(y)] = row
    return {"years": [str(y) for y in years], "months": MONTH_NAMES, "grid": grid}


def build_equity(df: pd.DataFrame) -> list[dict]:
    df = df.sort_values("t").copy()
    df["cum"] = df["pnl"].cumsum()
    df["peak"] = df["cum"].cummax()
    df["dd"] = df["cum"] - df["peak"]
    return [
        {"t": t.strftime("%Y-%m-%d %H:%M"),
         "cum": round(float(c), 2),
         "dd": round(float(d), 2)}
        for t, c, d in zip(df["t"], df["cum"], df["dd"])
    ]


def analyze(trades_path: Path) -> dict:
    df = load_trades(trades_path)

    total_pnl = float(df["pnl"].sum())
    wins = int((df["pnl"] > 0).sum())
    n = int(len(df))

    monthly = build_monthly_candles(df)
    best_month = max(monthly, key=lambda r: r["month_pnl"]) if monthly else None
    worst_month = min(monthly, key=lambda r: r["month_pnl"]) if monthly else None

    # Best month-of-year (seasonality): aggregate across all years by calendar month.
    moy = []
    for m in range(1, 13):
        sub = df[df["month"] == m]
        moy.append({
            "month": MONTH_NAMES[m - 1],
            "pnl": round(float(sub["pnl"].sum()), 2),
            "trades": int(len(sub)),
            "win_rate": round(100 * (sub["pnl"] > 0).mean(), 1) if len(sub) else 0.0,
        })

    dow = _group_block(df, "dow")
    for r in dow:
        r["label"] = DOW_NAMES[int(r["key"])]
    dow = [r for r in dow if int(r["key"]) < 5] + [r for r in dow if int(r["key"]) >= 5]

    hour = _group_block(df, "entry_hour")
    for r in hour:
        r["label"] = f"{int(r['key']):02d}:00"

    direction = _group_block(df, "direction")
    for r in direction:
        r["label"] = r["key"]

    yearly = []
    for y, g in df.groupby("year"):
        yearly.append({
            "year": int(y),
            "pnl": round(float(g["pnl"].sum()), 2),
            "trades": int(len(g)),
            "win_rate": round(100 * (g["pnl"] > 0).mean(), 1),
            "total_r": round(float(g["r_gained"].sum()), 3),
        })

    return {
        "headline": {
            "trades": n,
            "wins": wins,
            "losses": n - wins,
            "win_rate": round(100 * wins / n, 2) if n else 0.0,
            "total_pnl": round(total_pnl, 2),
            "avg_pnl": round(total_pnl / n, 2) if n else 0.0,
            "total_r": round(float(df["r_gained"].sum()), 3),
            "profit_factor": _profit_factor(df["pnl"]),
            "best_month": best_month,
            "worst_month": worst_month,
            "date_from": df["t"].min().strftime("%Y-%m-%d"),
            "date_to": df["t"].max().strftime("%Y-%m-%d"),
        },
        "monthly_candles": monthly,
        "month_of_year": moy,
        "calendar": build_calendar(df),
        "day_of_week": dow,
        "hour_of_day": sorted(hour, key=lambda r: r["key"]),
        "direction": direction,
        "yearly": sorted(yearly, key=lambda r: r["year"]),
        "equity": build_equity(df),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description="Analyze sniper_bot_v2 backtest output")
    ap.add_argument("--trades", default=str(DEFAULT_TRADES))
    ap.add_argument("--out", default=str(OUT_DIR / "analysis.json"))
    args = ap.parse_args()

    trades_path = Path(args.trades)
    if not trades_path.exists():
        print(f"No trade log at {trades_path}. Run `python run.py backtest` first.")
        return 1

    data = analyze(trades_path)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(data, indent=2))

    h = data["headline"]
    print(f"Analyzed {h['trades']} trades  ({h['date_from']} -> {h['date_to']})")
    print(f"  Total P&L:     ${h['total_pnl']:,.2f}")
    print(f"  Win rate:      {h['win_rate']}%")
    print(f"  Profit factor: {h['profit_factor']}")
    if h["best_month"]:
        print(f"  Best month:    {h['best_month']['ym']}  ${h['best_month']['month_pnl']:,.2f}")
        print(f"  Worst month:   {h['worst_month']['ym']}  ${h['worst_month']['month_pnl']:,.2f}")
    print(f"\n  Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
